<a href="https://colab.research.google.com/github/shionguha/inf2178-expdesignfordatascience-w23/blob/main/ancova.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#ancova example 1
import numpy as np
import pandas as pd

# create data
data = pd.DataFrame({'methodology': np.repeat(['A', 'B', 'C'], 4),
					'current_grade': [67, 88, 75, 85,
									92, 77, 74, 88,
									91, 88, 82, 80],
					'test_score': [77, 89, 74, 69,
									88, 93, 94, 90,
									85, 81, 83, 79]})
# view data
data

   methodology  current_grade  test_score
0            A             67          77
1            A             88          89
2            A             75          74
3            A             85          69
4            B             92          88
5            B             77          93
6            B             74          94
7            B             88          90
8            C             91          85
9            C             88          81
10           C             82          83
11           C             80          79

In [12]:
from pingouin import ancova

data = pd.DataFrame({'methodology': np.repeat(['A', 'B', 'C'], 4),
					'current_grade': [67, 88, 75, 85,
									92, 77, 74, 88,
									91, 88, 82, 80],
					'test_score': [77, 89, 74, 69,
									88, 93, 94, 90,
									85, 81, 83, 79]})

ancova(data=data, dv='test_score', covar='current_grade', between='methodology')

          Source          SS  DF         F     p-unc       np2
0    methodology  387.510992   2  6.005703  0.025542  0.600228
1  current_grade    1.404669   1  0.043540  0.839927  0.005413
2       Residual  258.095331   8       NaN       NaN       NaN

In [13]:
#ancova example 2
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Define the data for the ANCOVA
df = pd.DataFrame({'dependent_variable' : [8, 7, 9, 11, 10, 12, 14, 13, 15, 16],
   'group' : ["A", "A", "A", "B", "B", "B", "C", "C", "C", "C"],
    'covariate' : [20, 30, 40, 30, 40, 50, 40, 50, 60, 70]})

# Perform the ANCOVA
model = ols('dependent_variable ~ group + covariate', data=df).fit()

# Print the summary of the model
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:     dependent_variable   R-squared:                       0.939
Model:                            OLS   Adj. R-squared:                  0.909
Method:                 Least Squares   F-statistic:                     31.00
Date:                Mon, 27 Feb 2023   Prob (F-statistic):           0.000476
Time:                        16:56:28   Log-Likelihood:                -10.724
No. Observations:                  10   AIC:                             29.45
Df Residuals:                       6   BIC:                             30.66
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.0000      1.054      5.692      0.001       3.421       8.579
group[T.B]     2.3333      0.805      2.898      0.027       0.363       4.303
group[T.C]     4.8333      1.032      4.684      0.003       2.308       7.358
covariate      0.0667      0.030      2.191      0.071      -0.008       0.141
==============================================================================
Omnibus:                        2.800   Durbin-Watson:                   2.783
Prob(Omnibus):                  0.247   Jarque-Bera (JB):                1.590
Skew:                          -0.754   Prob(JB):                        0.452
Kurtosis:                       1.759   Cond. No.                         201.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

/usr/local/lib/python3.8/dist-packages/scipy/stats/stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [15]:
#ancova example 3
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/ethanweed/pythonbook/main/Data/clintrial.csv")

pd.crosstab(index=df["drug"], columns=df["therapy"],margins=False)

therapy   CBT  no.therapy
drug
anxifree    3           3
joyzepam    3           3
placebo     3           3

In [16]:
round(df.groupby(['therapy', 'drug'])[['mood_gain']].mean(),2)

                     mood_gain
therapy    drug
CBT        anxifree       1.03
           joyzepam       1.50
           placebo        0.60
no.therapy anxifree       0.40
           joyzepam       1.47
           placebo        0.30

In [17]:
round(df.groupby(['therapy'])[['mood_gain']].mean(),2)

            mood_gain
therapy
CBT              1.04
no.therapy       0.72

In [18]:
round(df.groupby(['drug'])[['mood_gain']].mean(),2)

          mood_gain
drug
anxifree       0.72
joyzepam       1.48
placebo        0.45

In [19]:
round(df['mood_gain'].mean(),2)

0.88

In [21]:
import pingouin as pg
model1 = pg.anova(dv='mood_gain', between='drug', data=df, detailed=True)
round(model1, 2)

   Source    SS  DF    MS      F  p-unc   np2
0    drug  3.45   2  1.73  18.61    0.0  0.71
1  Within  1.39  15  0.09    NaN    NaN   NaN

In [22]:
model2 = pg.anova(dv='mood_gain', between=['drug', 'therapy'], data=df, detailed=True)
round(model2, 4)

           Source      SS  DF      MS        F   p-unc     np2
0            drug  3.4533   2  1.7267  31.7143  0.0000  0.8409
1         therapy  0.4672   1  0.4672   8.5816  0.0126  0.4170
2  drug * therapy  0.2711   2  0.1356   2.4898  0.1246  0.2933
3        Residual  0.6533  12  0.0544      NaN     NaN     NaN